//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int id_order { get; set; }
        public string Tip { get; set; }
        public string Materials { get; set; }
        public string Price_Zacup { get; set; }
        public string Price_Itog { get; set; }
        public string Status { get; set; }
        public Nullable<int> id_serv { get; set; }
    
        public virtual Servis Servis { get; set; }
    }
}
